spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/talkkid"
    userName: "root"
    password: "1q2w3e4r@"
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      generate-ddl: true # 테이블 생성을 가능하게 하겠다
      ddl-auto: update # 테이블을 어떻게 처리 할지 결정 # ddl-auto >> jpa 의 엔티티를 db 의 테이블을 맵핑을 해줌
      # 추후 서비스 할때에는 none 으로 설정해줌
    properties:
      hibernate:
        show_sql: true # 쿼리가 수행될때 SQL 도 같이 보여줌
        format_sql: true # SQL 을 보기 좋게 포멧팅
        dialect: org.hibernate.dialect.MySQLDialect # 여러 데이터베이스에 맞게 설정